### ISSUE TITLE
[Feature request] Allow Warden rules to operate on the bot

### ISSUE THREAD

**Issue by ase1590** [Twentysix26/x26-Cogs#100]
**Cog**
- [ x ] Defender
- [ ] Index
- [ ] Sbansync

**Describe the feature you'd like to see**
In an attempt to limit what channel level 3 users can run `customcom` commands, I attempted to do something to this effect to auto-delete bot responses with Warden scripting:

```yaml
?def wd add name: botspam-limiter
rank: 1
event: on-message
priority: 2
if:
  - user-id-matches-any: [<redbot_id_here>]
  - if-not:
    - channel-matches-any: [<botspam-chan-here>]
do:
  - delete-user-message:
```
However it seems that the bot cannot operate on itself in this manner. 

I would like to see, if possible, the ability to have the bot handle its own messages via Warden scripts.

**Comment by EternalllZM** [comment]
Bots listening to other bots or even itself has been agreed upon as bad design and this would likely not be implemented for those reasons, alongside many others.


Instead, you should replace customcom with a warden "command" using conditions `message-matches-any` and `user-has-any-role-in` alongside `send-message` for the action. Nested conditions could make it infinitely expandable within one single rule.

Example:
```yaml
name: cc-example
event: on-message
rank: 1
if:
  - user-has-any-role-in: [<level3_roleid>]
  - message-matches-any: ["!command"]
do:
  - send-message: [$channel_id, "Output"]
```

https://twentysix26.github.io/defender-docs/warden/examples/

**Comment by ase1590** [comment]
Yeah closing this. 
It was pointed out to me the `cleanup` cog contains `[p]cleanup self` that can be used to have the bot clean its own messages up. 

so this action block was used to do that:

```
  - delete-user-message:
  - issue-command:
     issue_as: 1234 #user id to run command as
     command: cleanup self 1
     destination: $channel_id
  - send-message: [$channel_id, "$user_mention Sorry, you are not allowed to use commands outside of <#1234> at this time."]
  - delete-last-message-sent-after: 20 seconds
```
