### ISSUE TITLE
[Feature request] Random responses for warden

### ISSUE THREAD

**Issue by stephanrenggli** [Twentysix26/x26-Cogs#17]
**Cog**
- [x] Defender
- [ ] Index
- [ ] Sbansync

**Describe the feature you'd like to see**
Add multiple possibilities for all message sending actions such as send-in-channel, dm-user, send-dm.
Like this warden could randomly choose one possible response and send it.

Maybe even an optional weight/probability parameter so you can control which message is more likely to be chosen.

As the configuration is in yaml something like this could work.

Without weight.
```
rank: 2
name: random-greeting
event: on-message
if:
  - message-matches-any: ["hello"]
do:
  - send-in-channel:
    - message: "hello $user_mention"
    - message: "greetings $user_mention"
    - message: "howdy $user_mention"
```

With optional weight parameter.
```
rank: 2
name: random-weighted-greeting
event: on-message
if:
  - message-matches-any: ["hello"]
do:
  - send-in-channel:
    - message: "hello $user_mention"
      weight: 80
    - message: "greetings $user_mention"
      weight: 10
    - message: "howdy $user_mention"
      weight: 10
```
