### ISSUE TITLE
[Feature request] Add CommentAnalysis as a condition.

### ISSUE THREAD

**Issue by Biune** [Twentysix26/x26-Cogs#25]
This will be useful for when a message passes a threshold and an attribute set by the condition. An example config;

```
rank: 2
name: SEVERE_TOXICITY above 80
event: [on-message]
if-all:
  - commentanalysis_attributes: "SEVERE_TOXICITY"
  - commentanalysis_threshold: 80
  - is-staff: false
do:
  - issue-command: "mute $user_id"
```
