### ISSUE TITLE
[Bug] Forum Recipient Error

### ISSUE THREAD

**Issue by EternalllZM** [Twentysix26/x26-Cogs#75]
**Cog**
- [X] Defender
- [ ] Index
- [ ] Sbansync

**Describe the bug**
Using the `notify-staff` action, it seems to have issues identifying the forum channel or author in some way to craft a message to notify about. 

**To Reproduce**
1. Create a rule targeting a forum channel which deletes a message and `notify-staff` as actions.
2. Have an alternate account execute the rule.
3. Message will delete. However, the `notify-staff` action will not execute.

**Expected behavior**
Behavior should be similar to a regular channel, message deletion and sending message to notification channel.

**Error Message**
```
[Warden] (test-rule): Failed to send message, I could not find the recipient.
```

**Comment by EternalllZM** [comment]
I left the title vague as I am not quite sure whether it's due to the forum channel itself or the `notify-staff` condition specifically.

**Comment by EternalllZM** [comment]
Upon further testing alongside the new `dev` branch thread actions, I believe this is just a consequence of the odd behavior exhibited via https://github.com/Twentysix26/x26-Cogs/issues/76

Have not been able to reproduce this in a test environment, but it does exist in prod.

This can likely be reproduced by `on-reaction-add` and reacting in a forum channel, where a message sends on the reaction addition. However, I am leaving this up in hopes this might assist when forum targeting is being fixed.

**Comment by EternalllZM** [comment]
I have been able to replicate this again using `send-message` action as well. I think it has something to do with attempting to pull the `$user_mention` variable from a post made inside a forum channel.

**Comment by EternalllZM** [comment]
Updating the description and deleting speculative comments that cannot be reproduced. The issue is caused by a `send-message` action pointing to a different channel when executed from a message sent in a forum channel.

```yaml
name: test-issue75
event: on-message
rank: 1
if:
  - message-matches-any: ["sdhjkgbskd"]
do:
  - delete-user-message:
  - send-message: [955301063991369788, "I was told to send here"] # ERROR
  - send-message: [$channel_id, "Can I send here?"] # DOES NOT ERROR
  - exit:
  ```
  Send "sdhjkgbskd" in a forum channel. Message deletes but the `send-message` into channelID 955301063991369788 never executes, errors out into `def monitor` with the following:
  ```rust
  [07/28 06:26:55] [Warden] (test-issue75): Failed to send message, I could not find the recipient.
  ```
